### PR TITLE
command.Command._run_local_command(): add environment variable RUNNING_INSIDE_AUTOMATIX=1

### PR DESCRIPTION
**Pull request by fkusei**
This allows tools and commands to evaluate whether they are running inside automatix and adjust their behaviour accordingly.

### CODE REVIEW

**Review by phosei — APPROVED** [review]
Gave it a quick test, LGTM.

**Comment by MaZderMind** [comment]
Es wäre cool, auch bei Remote-Commands die Env-Variable in der remote Shell zu setzen, so dass auch dort laufende Scripte die unterscheidung vornehmen können.

**Comment by vanadinit** [comment]
Hmm seems something is broken with the notifications. I did not get one for this PR review...

**Comment by vanadinit** [comment]
Ahh I see, ... it was requested from my abandoned seibert//-github account (j-p-a-u-l).

@fkusei @MaZderMind @sschmachtel If you want me to review the changes, please add this one (@vanadinit)

Cheers
Johannes

**Pull request merged**
