### PR TITLE
Add Progress bar

### PR DESCRIPTION
**Pull request by vanadinit**
Feature to add a "apt-like" progress bar.

Because I developed this feature based on the other advancements (see other PRs) this one also contains the other commits and changes.

### CODE REVIEW

**Comment by phosei** [comment]
Hello //S, do we want this feature? It pulls in a new dependency. Not sure if it’s worth the trouble.

Note: It looks like there’s a new feature hidden in this PR: `T` to spawn a shell. I’d argue that this isn’t really required – why not open a new terminal window?

**Comment by fkusei** [comment]
This PR should be split into three:
- add progress bar
- add `T` to spawn a new shell
- various other fixes

I'd request @vanadinit to rework this to separate PRs to be able to review this easier.

**Comment by vanadinit** [comment]
@fkusei @phosei Did you see my first comment on this and #59 ?

> Feature to add a "apt-like" progress bar.
> 
> Because I developed this feature based on the other advancements (see other PRs) this one also contains the other commits and changes.

Maybe you can first have a look on #59 , which deals with the `T` feature. Sorry for the confusion. If I recall it correctly @sschiller-seibert asked for something like this years ago? But maybe she asked for something similar?

Yes there is a new dependency on this progress_bar feature, but it's not necessary and just optional. The dependency itself is not really a big library. Maybe I will rewrite it in future and integrate it directly.

Even if I like the two features (terminal, progress_bar), I would describe these more as "comfort" advancements than really necessary.

Maybe @sschmachtel wants to test them and give feedback?

**Comment by MaZderMind** [comment]
(!) This PR includes changes from https://github.com/seibert-media/automatix/pull/59

**Comment by sschmachtel** [comment]
While I don't think I'll ever start a shell from automatix, I don't mind adding this. I'm a little unsure if we want to add this option to the promt as well, as it kind of gets "full" (don't count this as a strong disagree). What I really would find helpful to have a python shell/environment on keypress to debug stuff.

**Comment by vanadinit** [comment]
@sschmachtel Interesting idea. In which environment should this python shell start?
After short research I think, the python command environment should be suitable and possible, but mainly for inspection rather than changing. For the second I am not sure of the behavior. Might be easy, might be really hard to implement.

For access to the automatix source code objects/variables/functions for the debugging of the automatix 'core' program, I would prefer the functions of one's IDE, but I think you did not mean this anyway.

**Comment by vanadinit** [comment]
For your information: I am not going to proceed contributing to this repository directly any longer. I created a new fork at https://github.com/vanadinit/automatix_cmd where I integrated these and some more features.
Feel free to watch this fork and if there are interesting features: You are invited to cherry-pick and integrate them here. If you need help, just ask and I will see whether and how I can help.

**Comment by Ga570n** [comment]
As @vanadinit mentioned the feature in this pull-request is part of the fork. We will not merge the PR at the moment. So if you are interested in this feature have a look here: https://github.com/vanadinit/automatix_cmd

**Pull request closed without merging**
